added newPost page and started using components
Aamr-mohamed/blog-website pull request #8
Opened 2023-08-17 12:52 UTC by Aamr-mohamed

2023-08-17 13:07 UTC, se-omarayman requested changes
1. posts should have a title and a description.
2. posts should be linked to the user that created it, currently if im not logged in the user is saved as an empty string.
3. pics paths aren't saved in localstorage (check the saved path, it's C:\\fakepath\\) this is because a browser can't access the computer's disk, so adding images will be hard unless we have a real backend server to save the images to
4. add an indication to the user that the post was created (maybe alert)
5. post titles should be unique, so show an error if the post already exists in localstorage
6.

2023-08-17 13:07 UTC, se-omarayman commented on src/routes/Signup/signup.js
sus naming

2023-08-17 13:08 UTC, se-omarayman commented on src/routes/Signup/signup.js
> +import Buttonn from "../components/button";
sus naming

2023-08-17 13:10 UTC, se-omar commented on src/routes/Signup/signup.js
> +import Buttonn from "../components/button";
also the file name for the component should match the component name

2023-08-20 21:33 UTC, se-omarayman commented
in posts:
1. we need to store the user email, not the username bec. email is the unique key.
2. we need to store the time of creating the post, call it createdAt.
3. remove the select file page, since we can't store files in local storage

2023-08-21 09:44 UTC, merged